<LoginScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: 20
        spacing: 10

        Label:
            text: "Giriş Yap"
            font_size: 24

        TextInput:
            id: username
            hint_text: "Kullanıcı Adı"

        TextInput:
            id: password
            hint_text: "Şifre"
            password: True

        Button:
            text: "Giriş"
            on_release: root.manager.current = "home"
